stages:
  - build
  - test
  - nuget
  - publish

build debug:
  stage: build
  script:
  - ./build.sh --target Build-CI --configuration Debug
  cache:
    paths:
    - packages
    - tools
  except:
    - master
    - tags
    - /^release/.*$/
  tags:
    - osx
    - xamarin
    - xcode

test debug:
  stage: test
  script:
  - ./build.sh --target Run-Unit-Tests --configuration Debug
  cache:
    paths:
    - packages
    - tools
  except:
    - master
    - tags
    - /^release/.*$/
  dependencies:
  - build debug
  tags:
    - osx
    - xamarin
    - xcode

build release:
  stage: build
  script:
  - ./build.sh --target Build-CI --configuration Release
  cache:
    paths:
    - packages
    - tools
  only:
    - master
    - tags
    - /^release/.*$/
  artifacts:
    paths:
      - bin/
    expire_in: 30 minutes
  tags:
    - osx
    - xamarin
    - xcode

test release:
  stage: test
  script:
  - ./build.sh --target Run-Unit-Tests --configuration Debug
  cache:
    paths:
    - packages
    - tools
  only:
    - master
    - tags
    - /^release/.*$/
  dependencies:
  - build release
  tags:
    - osx
    - xamarin
    - xcode

nuget pack:
  stage: nuget
  script:
  - ./build.sh --target NuGet-Pack
  cache:
    paths:
    - packages
    - tools
  artifacts:
    paths:
    - UnifiedMaps.*.nupkg
    expire_in: 30 minutes
  only:
    - master
    - tags
    - /^release/.*$/
  dependencies:
  - build release
  tags:
    - osx
    - xamarin
    - xcode

nuget publish pre:
  environment: prerelease
  stage: publish
  script:
  - ./build.sh --target NuGet-Publish
  cache:
    paths:
    - packages
    - tools
  artifacts:
    paths:
    - UnifiedMaps.*.nupkg
  only:
    - master
    - /^release/.*$/
  dependencies:
  - nuget pack
  tags:
    - osx
    - xamarin
    - xcode

nuget publish:
  environment: production
  stage: publish
  script:
  - ./build.sh --target NuGet-Publish
  cache:
    paths:
    - packages
    - tools
  artifacts:
    paths:
    - UnifiedMaps.*.nupkg
  only:
    - tags
  dependencies:
  - nuget pack
  when: manual
  tags:
    - osx
    - xamarin
    - xcode