stages:
  - build
  - test
  - nuget

build debug:
  stage: build
  script:
  - ./build.sh --target Build-CI --configuration Debug
  cache:
    paths:
    - packages
    - tools
  except:
    - master
    - tags
    - /^release/.*$/
  tags:
    - osx
    - xamarin
    - xcode

test debug:
  stage: test
  script:
  - ./build.sh --target Run-Unit-Tests --configuration Debug
  cache:
    paths:
    - packages
    - tools
  except:
    - master
    - tags
    - /^release/.*$/
  dependencies:
  - build debug
  tags:
    - osx
    - xamarin
    - xcode

build release:
  stage: build
  script:
  - ./build.sh --target Build-CI --configuration Release
  cache:
    paths:
    - packages
    - tools
  only:
    - master
    - tags
    - /^release/.*$/
  artifacts:
    paths:
      - bin/
    expire_in: 30 minutes
  tags:
    - osx
    - xamarin
    - xcode

test release:
  stage: test
  script:
  - ./build.sh --target Run-Unit-Tests --configuration Debug
  cache:
    paths:
    - packages
    - tools
  only:
    - master
    - tags
    - /^release/.*$/
  dependencies:
  - build release
  tags:
    - osx
    - xamarin
    - xcode

nuget pack:
  stage: nuget
  script:
  - ./build.sh --target NuGet-Pack
  cache:
    paths:
    - packages
    - tools
  only:
    - master
    - tags
    - /^release/.*$/
  dependencies:
  - build release
  tags:
    - osx
    - xamarin
    - xcode