assembly_info:
  patch: false

image: Visual Studio 2017

environment:
  CAKE_SETTINGS_SKIPVERIFICATION: true
  api_key:
    secure: Y2galPIGOpTJkWxNHc4WCLD7XBhWbSN8wycewlocBpEU3U5WoDoJi4NZEbDONspD

install:
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t platform-tools
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t build-tools-25.0.6
  - echo y | "C:\Program Files (x86)\Android\android-sdk\tools\android.bat" update sdk -u -a -t android-25

build_script:
  - ps: .\build.ps1 -target Build-CI-AppVeyor -configuration Release -Verbosity diagnostic

after_deploy:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - ps: ($artifacts.values | Where-Object {($_.path -like '*.nupkg') -and  !($_.path -like '*.symbols.nupkg')}) | foreach-object {nuget.exe push $_.path -Source https://www.nuget.org/api/v2/package -ApiKey $env:api_key; if ($lastexitcode -ne 0) {throw}}

cache:
  - packages -> **\packages.config

deploy:
- provider: GitHub
  name: production
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: JXorCJQaX0uFaA3ENKYvcqJ6JWkqccSjBHQikiqckVpmZRNAFeSCQ43TjhvKPSgu
  draft: true
  force_update: true

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#notification-appveyor'
  on_build_status_changed: true

- provider: GitHubPullRequest
  auth_token:
    secure: JXorCJQaX0uFaA3ENKYvcqJ6JWkqccSjBHQikiqckVpmZRNAFeSCQ43TjhvKPSgu
