assembly_info:
  patch: false

image: Visual Studio 2015

build_script:
  - ps: Write-Host "Build starting"
  # - ps: .\build.ps1 -target Build-CI-AppVeyor -configuration Release
  - ps: Write-Host "Build completed"

cache:
  - packages\
  - C:\Users\appveyor\AppData\Local\Xamarin\

build:
  verbosity: minimal

test: off

deploy:
- provider: NuGet
  name: production
  on:
    appveyor_repo_tag: true
  api_key:
    secure: Y2galPIGOpTJkWxNHc4WCLD7XBhWbSN8wycewlocBpEU3U5WoDoJi4NZEbDONspD

- provider: GitHub
  name: production
  on:
    appveyor_repo_tag: true
  auth_token:
    secure: JXorCJQaX0uFaA3ENKYvcqJ6JWkqccSjBHQikiqckVpmZRNAFeSCQ43TjhvKPSgu
  draft: true
  force_update: true

notifications:
- provider: Slack
  incoming_webhook: https://hooks.slack.com/services/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
  channel: '#notification-appveyor'
  on_build_status_changed: true

- provider: GitHubPullRequest
  auth_token:
    secure: JXorCJQaX0uFaA3ENKYvcqJ6JWkqccSjBHQikiqckVpmZRNAFeSCQ43TjhvKPSgu